packages:
  - apps/*
  - packages/*
overrides:
  ioredis: ^5.11.1
allowBuilds:
  '@google/genai': true
  esbuild: true
  msedge-tts: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  youtube-dl-exec: true
